### PR TITLE
Fix tests and resolve a bug in ExecutionBroadcaster

### LINKED ISSUE #466: Tests are not executed properly
When executing `mix test` I am getting the following errors. 

```
 Quantum.ExecutionBroadcasterTest: failure on setup_all callback, all tests have been invalidated
     ** (EXIT from #PID<0.422.0>) exited in: ExUnit.CaptureLog.remove_capture(#PID<0.490.0>)
         ** (EXIT) {:error, :module_not_found}

Quantum.ExecutorTest: failure on setup_all callback, all tests have been invalidated
     ** (EXIT from #PID<0.3948.0>) exited in: ExUnit.CaptureLog.remove_capture(#PID<0.3949.0>)
         ** (EXIT) {:error, :module_not_found}
```

The same errors appear in all latest coveralls pipelines. **Notice that all remaining tests in the modules with issues are never executed and the tests appear as successful**

The culprits are the following tests. If I comment them out all other tests run without issues:

```
- Quantum.ExecutionBroadcasterTest: "invalid timezone will not create a crash"
- Quantum.ExecutorTest: "start_link/3 logs error"
- Quantum.ExucutorTest: "start_link/3 releases lock on error"
```

### PR DESCRIPTION
**Pull request by pnezis**
Includes the following changes:

- Make all tests work again (#466) (had to include `:crash_reason` in logger metadata, and remove the custom `:crash_reason` from `log_exception`
- Fix a bug in `ExecutionBroadcaster` . In case of invalid timezone no `state` was returned and as a result the `GenServer` was crashing:

```
22:41:29.638 [error] Invalid Timezone "foobar" provided for job :test.
22:41:29.655 [error] GenServer Jobex.Scheduler.ExecutionBroadcaster terminating
** (FunctionClauseError) no function clause matching in Quantum.ExecutionBroadcaster.sort_state/1
    (quantum) lib/quantum/execution_broadcaster.ex:299: Quantum.ExecutionBroadcaster.sort_state(:ok)
    (quantum) lib/quantum/execution_broadcaster.ex:170: Quantum.ExecutionBroadcaster.handle_event/2
    (quantum) lib/quantum/execution_broadcaster.ex:91: anonymous fn/2 in Quantum.ExecutionBroadcaster.handle_events/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (quantum) lib/quantum/execution_broadcaster.ex:90: Quantum.ExecutionBroadcaster.handle_events/3
    (gen_stage) lib/gen_stage.ex:2395: GenStage.consumer_dispatch/6
    (gen_stage) lib/gen_stage.ex:2574: GenStage.take_pc_events/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
```

Closes #466

### CODE REVIEW

File: lib/quantum/executor.ex [hunk 1]
```diff
@@ -159,15 +159,6 @@ defmodule Quantum.Executor do
...
-      case kind do
-        :throw -> {{:nocatch, reason}, stacktrace}
-        _ -> {reason, stacktrace}
-      end
-
-    Logger.error(
-      Exception.format(kind, reason, stacktrace),
-      crash_reason: crash_reason
-    )
+    Logger.error(Exception.format(kind, reason, stacktrace))
```
Comment (maennchen) [inline lib/quantum/executor.ex:162]: The crash reason metadata is actually quite important. Have a look at this PR: https://github.com/quantum-elixir/quantum-core/pull/464

We also discussed it together with Jose Va im via the mailing list.

Comment (pnezis) [reply lib/quantum/executor.ex:162]: According to the docs (https://hexdocs.pm/logger/Logger.html) `:crash_reason` **is always added automatically by Logger whenever possible**

Comment (maennchen) [reply lib/quantum/executor.ex:162]: @pnezis Except we're logging manually and it can't do it automatically.

https://groups.google.com/g/elixir-lang-core/c/pWz-uTVMEVM/m/QGXncxD1AQAJ

Comment (maennchen) [reply lib/quantum/executor.ex:162]:
```elixir
defmodule CaptureLogErrorTest do
  use ExUnit.Case

  require Logger

  import ExUnit.CaptureLog

  test "greets the world" do
    assert capture_log(fn ->
             try do
               raise "foo"
             rescue
               error in RuntimeError ->
                 reason = Exception.normalize(:error, error, __STACKTRACE__)

                 Logger.error(
                   Exception.format(:error, reason, __STACKTRACE__),
                   crash_reason: {reason, __STACKTRACE__}
                 )
             end
           end) =~ "foo"
  end
end
```

This produces no error for me. Does it for you?
```

Comment (maennchen) [reply lib/quantum/executor.ex:162]: Oh this only happens in Elixir < 1.10.

Then I'd rather just raise the elixir requirement.

Comment (maennchen) [reply lib/quantum/executor.ex:162]: Or detect the elixir version and only do it in Elixir `~> 1.10` with a `TODO` to remove the condition in the future.

Comment (pnezis) [reply lib/quantum/executor.ex:162]: I confirm it is an elixir 1.9 issue. I will add the version check and push

Comment (pnezis) [reply lib/quantum/executor.ex]: @maennchen Added the version check.

**Review by maennchen — APPROVED** [review]

**Comment by maennchen** [comment]
@pnezis Thanks a lot again!
