### PR TITLE
Solution: Support options configuration for unnamed job

### LINKED ISSUE #604: The last example of configuration fails normalization
Hello, in the docs there is one way of setting a job mentioned, which is not working:
```elixir
config :your_app, YourApp.Scheduler,
  jobs: [
    ...
    # Runs every midnight:
    {"@daily",                 {Backup, :backup, []}, state: :inactive}
  ]
```
My testing configuration:
```elixir
config :test_app, TestApp.Scheduler,
  jobs: [
    {"*/1 * * * *", {TestApp.Workers.EnqueueContracts, :prepare_job, []}, state: :inactive}
  ]
```
Error:
```
** (Mix) Could not start application test_app: TestApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: TestApp.Scheduler
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Quantum.Normalizer.normalize/2
            (quantum 3.5.0) lib/quantum/normalizer.ex:32: Quantum.Normalizer.normalize(%Quantum.Job{run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, overlap: true, timezone: :utc, name: #Reference<0.3696946988.2404384770.187641>, schedule: nil, task: nil, state: :active}, {"*/1 * * * *", {TestApp.Workers.EnqueueNftContracts, :prepare_job, []}, [state: :inactive]})
            (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
            (quantum 3.5.0) lib/quantum.ex:309: anonymous fn/3 in Quantum.scheduler_config/3
            (elixir 1.15.7) lib/keyword.ex:1145: Keyword.update_guarded/4
            (elixir 1.15.7) lib/keyword.ex:1149: Keyword.update_guarded/4
            (quantum 3.5.0) lib/quantum.ex:306: Quantum.scheduler_config/3
            (crypto_hub 0.1.0) deps/quantum/lib/quantum.ex:357: CryptoHub.Scheduler.start_link/1
            (stdlib 5.2) supervisor.erl:420: :supervisor.do_start_child_i/3
            (stdlib 5.2) supervisor.erl:406: :supervisor.do_start_child/2
            (stdlib 5.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 5.2) supervisor.erl:1258: :supervisor.children_map/4
            (stdlib 5.2) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
            (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

### PR DESCRIPTION
**Pull request by fly49**
Closes  #604

### CODE REVIEW

File: test/quantum/normalizer_test.exs [hunk 1]
```diff
@@ -143,10 +143,13 @@ defmodule Quantum.NormalizerTest do
   test "unnamed job as tuple with arguments" do
```
Comment (fly49) [inline test/quantum/normalizer_test.exs:143]: I edited this test because it was exactly the same as on line 133
https://github.com/quantum-elixir/quantum-core/blob/663170438b234df7060c0b39ac856a501f0f05a6/test/quantum/normalizer_test.exs#L133

File: lib/quantum/normalizer.ex [hunk 2]
```diff
@@ -51,6 +51,18 @@ defmodule Quantum.Normalizer do
     normalize_options(base, %{schedule: schedule, task: task})
   end
 
+  def normalize(%Job{} = base, {schedule, task, opts}) when is_list(opts) do
+    if Keyword.keyword?(opts) do
```
Comment (maennchen) [inline lib/quantum/normalizer.ex:55]: Why do we need this check?

Comment (fly49) [reply lib/quantum/normalizer.ex:55]: To avoid errors in case this config is passed
```
{"@daily", {Backup, :backup, []}, [1, 2, 3]}}
```
I would add this keyword list check as a guard if it was possible
I can remove it if you prefer to crash instead of ignoring

Comment (maennchen) [reply lib/quantum/normalizer.ex:55]: @fly49 Silently ignoring the options if invalid does not seem like a good option to me. I'd rather have a crash instead.

**Review by maennchen — APPROVED** [review]
